-file("/usr/local/Cellar/erlang/18.1/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(cypher_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("lib/cypher/lexers/cypher_lexer.xrl", 40).

%% Remove quotation marks from a string
remove_quotes(Chars) ->
  re:replace(
    re:replace(
      strip_whitespace(Chars),
      "[\"\'\`]$",
      "",
      [{return, list}]
    ),
    "^[\"\'\`]",
    "",
    [{return, list}]
  ).

%% Remove the first char from a string
tail([_|T]) ->
  T.

%% Strip spaces
strip_whitespace(Chars) ->
  string:strip(Chars, both, $ ).

% Produce a key/value tuple
key_value([_|Chars]) ->
  [Key, Value] = string:tokens(Chars, ":"),
  [ remove_quotes(Key), remove_quotes(Value) ].

-file("/usr/local/Cellar/erlang/18.1/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,_L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L0, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L0, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L0, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("lib/cypher/lexers/cypher_lexer.erl", 311).
yystate() -> 55.

yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,70};
yystate(69, [110|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(69, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,69};
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [82|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,68};
yystate(67, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(67, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(67, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(67, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 81 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(67, [C|Ics], Line, Tlen, Action, Alen) when C >= 83, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(67, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(67, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,67};
yystate(66, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(65, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(64, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line+1, Tlen+1, Action, Alen);
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 8 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 31 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 38 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 45 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 91 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 95 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(64, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,64};
yystate(63, [32|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 26, Tlen);
yystate(63, [13|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 26, Tlen);
yystate(63, [9|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 26, Tlen);
yystate(63, [10|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,63};
yystate(62, [96|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [92|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [39|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [34|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(15, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(15, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 38 ->
    yystate(15, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(15, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 95 ->
    yystate(15, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97 ->
    yystate(15, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,62};
yystate(61, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(60, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(59, [79|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 5, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,59};
yystate(58, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(58, [85|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 5, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,58};
yystate(57, [119|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 118 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 120, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(57, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,57};
yystate(56, [97|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,56};
yystate(55, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line+1, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 69, C =< 76 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 78, C =< 81 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 83, C =< 90 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 100, C =< 114 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 116, C =< 122 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 110 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 112, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,54};
yystate(53, [105|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 5, Tlen);
yystate(53, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,53};
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(52, [78|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,52};
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(51, [72|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 71 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 73, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,51};
yystate(50, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(49, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(48, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(47, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line+1, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 38 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 95 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [96|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [92|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [47|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [46|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [39|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [34|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 38 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 45 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(46, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 91 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 95 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,46};
yystate(45, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(44, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(44, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,44};
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(43, [80|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 79 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 81, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,43};
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, [84|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, [77|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 76 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 78, C =< 83 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,42};
yystate(41, [97|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 5, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,41};
yystate(40, [109|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 5, Tlen);
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,40};
yystate(39, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(38, [109|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 5, Tlen);
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,38};
yystate(37, [103|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 5, Tlen);
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,37};
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(36, [79|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 5, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,36};
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(35, [67|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 5, Tlen);
yystate(35, [65|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(35, [66|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 68, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,35};
yystate(34, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, [62|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 19, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,33};
yystate(32, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line+1, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 8 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 31 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 38 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 45 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 91 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 95 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line+1, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line+1, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 38 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 95 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(30, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,30};
yystate(29, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line+1, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 38 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 95 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,29};
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(28, [86|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 5, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 85 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 87, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,28};
yystate(27, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 81 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 83, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 68 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 70, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,26};
yystate(25, [105|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,25};
yystate(24, [101|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,24};
yystate(23, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(22, [109|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 5, Tlen);
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,22};
yystate(21, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 100 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 102, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(20, [84|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 5, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,20};
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(19, [84|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 5, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,19};
yystate(18, [96|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, [45|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, [39|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, [34|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(18, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(18, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,18};
yystate(17, [46|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 0, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(17, Ics, Line, Tlen+1, 0, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,17};
yystate(16, [58|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 2, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,16};
yystate(15, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line+1, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 38 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 95 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, [96|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, [92|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, [58|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, [39|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, [34|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 2, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 38 ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 91 ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 95 ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97 ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,14};
yystate(13, [96|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, [92|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, [58|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, [39|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, [34|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, [10|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line+1, Tlen+1, 2, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(47, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(47, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 38 ->
    yystate(47, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 57 ->
    yystate(47, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 91 ->
    yystate(47, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 95 ->
    yystate(47, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 97 ->
    yystate(47, Ics, Line, Tlen+1, 2, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,13};
yystate(12, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(12, [69|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,12};
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(11, [69|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 5, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,11};
yystate(10, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(9, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, [104|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 5, Tlen);
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,8};
yystate(7, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 100, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(7, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,7};
yystate(6, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(5, [116|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(5, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,5};
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(4, [65|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 5, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, 5, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,4};
yystate(3, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 66, C =< 90 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, [96|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [92|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [47|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [46|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [39|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [34|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [10|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line+1, Tlen+1, 4, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(47, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(47, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 38 ->
    yystate(47, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 45 ->
    yystate(47, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 91 ->
    yystate(47, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 95 ->
    yystate(47, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97 ->
    yystate(47, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,2};
yystate(1, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(0, [46|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 4, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, 4, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, _) ->
    yyaction_20();
yyaction(21, _, _, _) ->
    yyaction_21();
yyaction(22, _, _, _) ->
    yyaction_22();
yyaction(23, _, _, _) ->
    yyaction_23();
yyaction(24, _, _, _) ->
    yyaction_24();
yyaction(25, _, _, _) ->
    yyaction_25();
yyaction(26, _, _, _) ->
    yyaction_26();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 10).
yyaction_0(TokenChars, TokenLine) ->
     { token, { number, TokenLine, TokenChars } } .

-compile({inline,yyaction_1/2}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 11).
yyaction_1(TokenChars, TokenLine) ->
     { token, { label, TokenLine, remove_quotes (tail (TokenChars)) } } .

-compile({inline,yyaction_2/2}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 12).
yyaction_2(TokenChars, TokenLine) ->
     { token, { string, TokenLine, remove_quotes (TokenChars) } } .

-compile({inline,yyaction_3/2}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 13).
yyaction_3(TokenChars, TokenLine) ->
     { token, { attribute, TokenLine, key_value (TokenChars) } } .

-compile({inline,yyaction_4/2}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 14).
yyaction_4(TokenChars, TokenLine) ->
     { token, { attribute, TokenLine, key_value (TokenChars) } } .

-compile({inline,yyaction_5/2}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 15).
yyaction_5(TokenChars, TokenLine) ->
     { token, { variable, TokenLine, TokenChars } } .

-compile({inline,yyaction_6/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 16).
yyaction_6(TokenLine) ->
     { token, { create, TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 17).
yyaction_7(TokenLine) ->
     { token, { match, TokenLine } } .

-compile({inline,yyaction_8/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 18).
yyaction_8(TokenLine) ->
     { token, { return, TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 19).
yyaction_9(TokenLine) ->
     { token, { node_open, TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 20).
yyaction_10(TokenLine) ->
     { token, { node_close, TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 21).
yyaction_11(TokenLine) ->
     { token, { attributes_open, TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 22).
yyaction_12(TokenLine) ->
     { token, { attributes_close, TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 23).
yyaction_13(TokenLine) ->
     { token, { comma, TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 24).
yyaction_14(TokenLine) ->
     { token, { end_of_command, TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 25).
yyaction_15(TokenLine) ->
     { token, { relationship_open, TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 26).
yyaction_16(TokenLine) ->
     { token, { relationship_close, TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 27).
yyaction_17(TokenLine) ->
     { token, { parent_of, TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 28).
yyaction_18(TokenLine) ->
     { token, { child_of, TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 29).
yyaction_19(TokenLine) ->
     { token, { related_to, TokenLine } } .

-compile({inline,yyaction_20/0}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 30).
yyaction_20() ->
     skip_token .

-compile({inline,yyaction_21/0}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 31).
yyaction_21() ->
     skip_token .

-compile({inline,yyaction_22/0}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 32).
yyaction_22() ->
     skip_token .

-compile({inline,yyaction_23/0}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 33).
yyaction_23() ->
     skip_token .

-compile({inline,yyaction_24/0}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 34).
yyaction_24() ->
     skip_token .

-compile({inline,yyaction_25/0}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 35).
yyaction_25() ->
     skip_token .

-compile({inline,yyaction_26/0}).
-file("lib/cypher/lexers/cypher_lexer.xrl", 36).
yyaction_26() ->
     skip_token .

-file("/usr/local/Cellar/erlang/18.1/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl", 290).
